language: node_js
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
node_js:
  - "10"
cache:
  directories:
    - node_modules  
install:
  - sudo pip3 install --upgrade awscli
jobs:
  include:
    - stage: "Deploy"
      name: "Deploy to www.gffny.com"
      if: branch == master
      script: "./deploy.sh"